# Generated by Django 5.0.4 on 2024-04-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_type',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
