# Generated by Django 5.0.4 on 2024-04-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0002_vehicle_type_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_type',
            name='image',
            field=models.ImageField(default=1, upload_to='vehicles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle_type',
            name='register_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
