# Generated by Django 5.0.4 on 2024-04-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0004_alter_vehicle_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_type',
            name='image',
            field=models.ImageField(upload_to='cars/'),
        ),
    ]
